---
AWSTemplateFormatVersion: 2010-09-09
Description: "Fargate for serverless bastion"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: SSH Configuration
        Parameters:
          - Password

Parameters:
  Password:
    Description: SSH password
    Type: String
  Vpc:
    Type: 'AWS::EC2::VPC::Id'
    Description: An existing VPC
    Default: vpc-2bcfac53
  PrivateSubnets:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: Two private subnets associated with the VPC
    Default: subnet-5462ba7b,subnet-1198fc5a

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroup for Bastion host
      VpcId: !Ref Vpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"

  CloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 1

  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref AWS::StackName

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Path: /

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: deny-all
          PolicyDocument:
            Statement:
              - Effect: Deny
                Action: "*"
                Resource: "*"
      Path: /

  Task:
    Type: AWS::ECS::TaskDefinition
    Properties: 
      Family: !Ref AWS::StackName
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      TaskRoleArn: !Ref TaskRole
      ExecutionRoleArn: !Ref TaskExecutionRole
      Cpu: 256
      Memory: 512
      ContainerDefinitions:
        - Name: bastion
          Image: fijimunkii/fargate-shell:latest
          Command:
            - "-d"
          PortMappings: 
            - ContainerPort: 22
              HostPort: 22
          Environment:
            - Name: SSH_PASSWORD
              Value: !Ref Password
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref CloudWatchLogsGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: bastion
          Essential: true

  Service:
    Type: AWS::ECS::Service
    Properties:
      LaunchType: FARGATE
      Cluster: !Ref Cluster
      DesiredCount: 1
      TaskDefinition: !Ref Task
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets: !Ref PrivateSubnets
          SecurityGroups: 
            - !Ref SecurityGroup
